using FantasyModuleParser.NPC;
using FantasyModuleParser.NPC.Models.Action;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FantasyModuleParser.Importer.NPC
{
    public class ImportEngineerSuiteNPC
    {
        public ImportEngineerSuiteNPC()
        {

        }

        /// <summary>
        /// Parses & Imports data from .npc files generated by Engineer Suite - NPC Module by Maasq
        /// </summary>
        /// <param name="engineerSuiteNpcFileContent">The file content of an *.npc file created by the NPC Engineer module in Engineer Suite</param>
        /// <returns></returns>
        public NPCModel ParseEngineerSuiteNPCContent(string engineerSuiteNpcFileContent)
        {
            NPCModel parsedNPCModel = new NPCModel();
            return parsedNPCModel;
        }
    }
}
