using FantasyModuleParser.Equipment.Models;
using FantasyModuleParser.Main.Models;
using FantasyModuleParser.NPC;
using FantasyModuleParser.Spells.Models;
using System.Collections.Generic;
using System.IO;
using System.Xml;

namespace FantasyModuleParser.Exporters
{
	public class DatabaseExporter
	{
        public static void DatabaseXML(XmlWriter xmlWriter, ModuleModel module)
		{
			xmlWriter.WriteStartDocument();
			DatabaseXML_Comments(xmlWriter);
			DatabaseXML_Root(xmlWriter, module);
			xmlWriter.WriteEndDocument();
			xmlWriter.Close();
		}

		private static void DatabaseXML_Comments(XmlWriter xmlWriter)
		{
			xmlWriter.WriteComment("Generated by Fantasy Module Parser");
			xmlWriter.WriteComment("Written by Theodore Story, Darkpool, and Battlemarch (c) 2021");
		}

		private static void DatabaseXML_Root(XmlWriter xmlWriter, ModuleModel module)
		{
			xmlWriter.WriteStartElement("root"); // <root>
			xmlWriter.WriteAttributeString("version", "4.0"); /* <root version="4.0"> */
			ImageExporter.DatabaseXML_Root_Image(xmlWriter, module);
			EquipmentExporter.DatabaseXML_Root_Item(xmlWriter, module);
			NPCExporter.DatabaseXML_Root_Npc(xmlWriter, module);
			SpellExporter.DatabaseXML_Root_Spell(xmlWriter, module);
			TableExporter.DatabaseXML_Root_Tables(xmlWriter, module);
			// EquipmentExporter.DatabaseXML_Root_Reference_EquipmentLists(xmlWriter, module);
			// ImageExporter.DababaseXML_Root_Reference_Imagelists(xmlWriter, module);
			// NPCExporter.DatabaseXML_Root_Reference_NPClists(xmlWriter, module);
			// SpellExporter.DatabaseXML_Root_Reference_Spelllists(xmlWriter, module);
			ReferenceExporter.DatabaseXML_Root_Reference(xmlWriter, module);
			LibraryExporter.Database_Library(xmlWriter, module);
			xmlWriter.WriteEndElement(); // Closes </root>
		}
	}
}
